### ISSUE TITLE
網址須更動以配合中央氣象局改制為中央氣象署

### ISSUE THREAD

**Issue by ttzeng** [ttzeng/chat-bot#9]
```
"Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 130, in view_func
    return function(request._get_current_object())
  File "/workspace/main.py", line 50, in chat
    return jsonify({ 'fulfillmentText': chat_bot(request.get_json()) })
  File "/workspace/chat_bot.py", line 51, in chat_bot
    reply = query_weather(location, startTime, endTime, weather)
  File "/workspace/chat_bot.py", line 66, in query_weather
    r = s.get(url, headers = opendata_access_token, params = params).json()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opendata.cwb.gov.tw', port=443): Max retries exceeded with url: /api/v1/rest/datastore/F-D0047-091?format=json&elementName=MinT%2CMaxT%2CWx%2CPoP12h&locationName=%E8%87%BA%E5%8C%97%E5%B8%82 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x3e3edcde01f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
timestamp: "2024-06-08T13:32:37.306830Z"
```

**Comment by ttzeng** [comment]
2023年6月7日[總統令公告](https://www.president.gov.tw/Page/78?DeteailNo=1&Keywords=11200046741)，同年9月15日氣象局升格為中央氣象署，氣象資料開放平台資料下載URL與各項API服務均改為`https://opendata.cwa.gov.tw/`，舊cwb網址自2024年1月1日起失效。
